# Generated by Django 5.1.1 on 2024-09-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_contenido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='estados',
            new_name='estado',
        ),
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.URLField(max_length=355),
        ),
    ]
